
trigger: none
pool:
  name: "DevOps-Agents-VM"

stages:

- stage: Build_BasketMS
  jobs:
  - job: Build_BasketMS
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'