# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      # - uses: action/checkout@v3
      # - name: Setup .Net Core
      #   uses: actions/setup-dotnet@v3
      #   with: 
      #     dotnet-version: 8.0.x
          
      - name: Restore
        run: dotnet restore ./DesktopApp/APP/PizzaPlace/PizzaPlace.csproj
      - name: Build
        run: dotnet build ./DesktopApp/APP/PizzaPlace/PizzaPlace.csproj
      - name: Pack
        run: dotnet pack ./DesktopApp/APP/PizzaPlace/PizzaPlace.csproj
      - name: Publish
        run: dotnet publish ./DesktopApp/APP/PizzaPlace/PizzaPlace.csproj --configuration Release --output ./publish
      - name: Add Source
        run: dotnet nuget add source --username chitulescui --password ${{ secrets.pipelineconnect }} --store-password-in-clear-text --name github2 "https://nuget.pkg.github.com/NAMESPACE/index.json" 
      - name: push  
        run: dotnet nuget push ./DesktopApp/APP/PizzaPlace/bin/Release/PizzaPlace.1.0.0.nupkg  --api-key ${{secrets.pipelineconnect}} --source github




    
    # - name: setup-msbuild
    #   uses: microsoft/setup-msbuild@v2
    # - name: .Net Build
    #   uses: EasyDesk/action-dotnet-build@v1.0.0
    #   with:
    #     build-args: PizzaPlace.csproj
    # - name: Test
    #   working-directory: chitulescui\PizzaPlace-Azure-DevOps-Pipelines\DesktopApp\APP\PizzaPlace
    #   run: dotnet test --no-build --verbosity normal
      
      
          
