# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: restore
      working-directory: chitulescui\PizzaPlace-Azure-DevOps-Pipelines\DesktopApp\APP\PizzaPlace\*.csproj
      run: dotnet restore
    - name: Build
      working-directory: chitulescui\PizzaPlace-Azure-DevOps-Pipelines\DesktopApp\APP\PizzaPlace\*.csproj
      run: dotnet build --no-restore
    - name: Test
      working-directory: chitulescui\PizzaPlace-Azure-DevOps-Pipelines\DesktopApp\APP\PizzaPlace\*.csproj
      run: dotnet test --no-build --verbosity normal
