name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
jobs:
  build:

    runs-on: ["self-hosted","Linux","X64"]
    steps:
    - uses: actions/checkout@v4
      with:
          repository: ${{ github.repository }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: vchitulescu2@gmail.com
          password: ${{ secrets.SECRET_DOCKER }}
    - name: Build 
      working-directory: WebApp/
      run: docker build . --file Dockerfile --tag webapp:latest
    - name: Push
      run: docker push Dockerfile/webapp:latest
    
   
