name: Push docker image to hub 

on:
  push:
    branches: [ "second" ]
  pull_request:
    branches: [ "second" ]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
jobs:
  build:

    runs-on: ["self-hosted","Linux","X64"]
    steps:
    - uses: actions/checkout@v4
      with:
          repository: ${{ github.repository }}
    - name: Login to Docker Hub
      run: docker login -u chitulescui -p ${{ secrets.SECRET_DOCKER }}
    - name: Build 
      working-directory: WebApp/
      run: docker build . --file Dockerfile --tag webapp
    - name: Tag
      run: docker tag webapp chitulescui/webapp:webapp
    - name: Push
      run: docker push chitulescui/webapp:webapp
    
   
