name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
jobs:
  build:

    runs-on: ["self-hosted","Linux","X64"]
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: chitulescui
          password: ${{ secrets.SECRET_DOCKER }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
          tags: webapp/webapp:latest
      # uses: docker/build-push-action@v5
      # with:
      #     push: true
      #     tags: webapp/webapp:latest

    
   
