name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
jobs:
  build:

    runs-on: ["self-hosted","Linux","X64"]
    steps:
    - uses: actions/checkout@v4
      with:
          repository: ${{ github.repository }}
    - name: Login to Docker Hub
      run: docker login -u chitulescui -p ${{ secrets.SECRET_DOCKER }}
    - name: Build 
      working-directory: WebApp/
      run: docker build . --file Dockerfile --tag webapp:latest
    - name: Tag
      run: docker tag webapp:latest githubreposwk/webapp:latest
    - name: Logout
      run: docker logout
    - name: Login to Docker Hub
      run: docker login -u chitulescui -p ${{ secrets.SECRET_DOCKER }}
    - name: Push
      run: docker push githubreposwk/webapp:latest
    
   
